version: '3'
services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: postgres  # Use your 'postgres' database name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow:
    image: puckel/docker-airflow:1.10.9
    environment:
      - AIRFLOW_DB_TYPE=postgres
      - AIRFLOW_DB_HOST=postgres
      - AIRFLOW_DB_PORT=5432
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
      - AIRFLOW_DB_NAME=postgres  # Use your 'postgres' database name
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
